### POST Request to create a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Dili Boy",
  "email": "dili@example.com",
  "address": "123 Main Street",
  "dateOfBirth": "1996-06-10",
  "registeredDate": "2025-06-11"
}
